# Generated by Django 5.0.1 on 2024-02-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'verbose_name': 'Job Seeker'},
        ),
    ]
