# Generated by Django 5.0.1 on 2024-02-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('application', 'question')},
        ),
    ]
