name: React CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0" # Update Node.js version to 16

      - name: Install Dependencies
        working-directory: frontend
        run: |
          cd frontend
          npm install

      - name: Run Tests
        working-directory: frontend
        run: npm test
